### PR TITLE
Support for adding SCP liquidiy provision orders into OBA instances.

### PR DESCRIPTION
**Pull request by marcovc**

### CODE REVIEW

**Review by josojo — APPROVED** [review]
really nice Marco. Thanks!

LGTM!

For the batch iterator, you are checking just the timestamps. It would be great to also ensure that not more than 50 orders - here I am only counting market orders from retail customers(swaps) - are in batch, as we can not settle more than that on-chain.

**Comment by marcovc** [comment]
> For the batch iterator, you are checking just the timestamps. It would be great to also ensure that not more than 50 orders - here I am only counting market orders from retail customers(swaps) - are in batch, as we can not settle more than that on-chain.

Since it seems non-trivial to find what is the optimal subset of 50 orders we should pick, perhaps we can do as before - create problem instances with an unbounded number of orders, and then as part of the solution process or some preprocessing step restrict them to those 50 orders?

50 only? :(

**Comment by josojo** [comment]
>Since it seems non-trivial to find what is the optimal subset of 50 orders we should pick, perhaps we can do as before - create problem instances with an unbounded number of orders, and then as part of the solution process or some preprocessing step restrict them to those 50 orders?

But we want to settle all retail customer orders, as they should have the "uniswap" experience. Hence, it think it makes sense to keep batches small from the start and have the guarantee that we can always settle them at once.

>50 only? :(

The settlement of more orders does not fit into one block.

**Comment by fleupold** [comment]
>  it seems non-trivial to find what is the optimal subset of 50 orders we should pick

Maybe we can for now just order by size? I'd argue that we could even split any batch that has >50 orders in two batches as in the system we won't enforce a certain "batch time". Thus when there is a lot of demand we could settle up to one batch per block.

**Comment by marcovc** [comment]
Will open a new issue for the "splitting" since it seems there's more one way to do it.

**Pull request merged**
